import { useState, useEffect, useCallback, useRef, useMemo, startTransition, type SetStateAction } from "react";
import { ChevronsUpDown } from "lucide-react";
import { DigitalClock } from "@/components/digital-clock";
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  MouseSensor,
  TouchSensor,
  useSensor,
  useSensors,
  DragEndEvent,
  DragOverlay,
  DragStartEvent,
  DragCancelEvent,
} from "@dnd-kit/core";
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
  useSortable,
  rectSortingStrategy,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { getAllCities, getCityByKey, searchCities, getTimeInCityZone, formatCityDisplay, formatCityDetail, loadCities, loadTopCities, areCitiesLoaded, areSearchCitiesReady, didFullCitiesFail, type TimezoneOption } from "@/lib/city-lookup";
import { cacheTileMetadata, getCityOrCachedTile } from "@/lib/tile-cache";
import { resolveLocalCity } from "@/lib/closest-city";
import { track } from "@/lib/analytics";
import { ShareSelectionBar } from "@/components/share-selection-bar";

// Track recent touch events so we can suppress synthetic mouse events on mobile.
// Browsers fire mousedown ~0-100ms after touchstart; if MouseSensor activates on
// that synthetic event, it cancels pending TouchSensor activations.
let recentTouchTimestamp = 0;
if (typeof document !== "undefined") {
  document.addEventListener("touchstart", () => { recentTouchTimestamp = Date.now(); }, { passive: true });
}

// Desktop-only mouse sensor: ignores synthetic mouse events generated by touch
class DesktopMouseSensor extends MouseSensor {
  static activators = [
    {
      eventName: "onMouseDown" as const,
      handler: ({ nativeEvent }: { nativeEvent: MouseEvent }) => {
        // Synthetic mouse events from touch fire within ~500ms of touchstart
        if (Date.now() - recentTouchTimestamp < 1000) return false;
        return true;
      },
    },
  ];
}

// Custom touch sensor: activates only on the drag handle (150ms)
class HandleTouchSensor extends TouchSensor {
  static activators = [
    {
      eventName: "onTouchStart" as const,
      handler: ({ nativeEvent }: { nativeEvent: TouchEvent }) => {
        const target = nativeEvent.target as HTMLElement;
        return !!target.closest("[data-drag-handle]");
      },
    },
  ];
}

// Custom touch sensor: activates on the whole tile (350ms), excluding interactive elements and the handle
class TileTouchSensor extends TouchSensor {
  static activators = [
    {
      eventName: "onTouchStart" as const,
      handler: ({ nativeEvent }: { nativeEvent: TouchEvent }) => {
        const target = nativeEvent.target as HTMLElement;
        if (target.closest("[data-no-drag]")) return false;
        if (target.closest("[data-drag-handle]")) return false;
        return true;
      },
    },
  ];
}

interface TimeZoneConverterProps {
  isCustomMode: boolean;
  selectedTime: Date | null;
  onTimeUpdate: (zoneKey: string, hours: number, minutes: number) => void;
  onReset: () => void;
  use24Hour: boolean;
  sortEastToWest: boolean;
  onSortEastToWestChange: (value: boolean) => void;
  showRelativeTime: boolean;
  selectedZones: string[];
  onZonesChange: (zones: SetStateAction<string[]>) => void;
  /** Geolocation is resolved here, but the notice is shown in SiteFooter — a sibling of this
   *  component, not a descendant — so the flag is reported upward rather than held locally. */
  onGeoDeniedChange?: (denied: boolean) => void;
  /** Share select-mode lives here, but the drawer toggle (which grays out during it) lives in
   *  the page above — so the active flag is reported upward, mirroring onGeoDeniedChange. */
  onShareModeChange?: (active: boolean) => void;
  /** Cities to flash on arrival, driven from outside — the Sharing View hands over several at
   *  once when a shared link is accepted. The local highlight (adding one city by hand) stays
   *  separate: it's a different event that happens to reuse the same animation. */
  highlightedZones?: string[];
  /** Fired on a real manual add (not a duplicate or a cap-hit). The page uses it to raise the
   *  account Registration Bar; the add itself flows through onZonesChange as before. */
  onClockAdded?: () => void;
}

interface SortableClockItemProps {
  id: string;
  zoneKey: string;
  index: number;
  baseTime: Date;
  heroDate: Date;
  isNew: boolean;
  isHighlighted: boolean;
  onZoneChange: (index: number, zoneKey: string) => void;
  onTimeUpdate: (zoneKey: string, hours: number, minutes: number) => void;
  onRemove?: (zoneKey: string) => void;
  onShare: (zoneKey: string) => void;
  isSelectMode: boolean;
  isSelected: boolean;
  onToggleSelect: (zoneKey: string) => void;
  allZones: string[];
  isDragActive: boolean;
  isCustomMode: boolean;
  use24Hour: boolean;
  heroOffset: number;
  showRelativeTime: boolean;
}

function SortableClockItem({
  id,
  zoneKey,
  index,
  baseTime,
  heroDate,
  isNew,
  isHighlighted,
  onZoneChange,
  onTimeUpdate,
  onRemove,
  onShare,
  isSelectMode,
  isSelected,
  onToggleSelect,
  allZones,
  isDragActive,
  isCustomMode,
  use24Hour,
  heroOffset,
  showRelativeTime,
}: SortableClockItemProps) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id });

  const style = {
    transform: CSS.Translate.toString(transform),
    transition,
    opacity: isDragging ? 0.5 : 1,
  };

  const city = getCityOrCachedTile(zoneKey);

  // In select mode dragging is off, so the wrapper doesn't carry the drag attributes/listeners.
  const dragProps = isSelectMode ? {} : { ...attributes, ...listeners };

  return (
    <div
      ref={setNodeRef}
      style={style}
      {...dragProps}
      // my-[3px] is breathing room between stacked tiles, not part of the tile: it rides the grid
      // wrapper so the tile's own box (and the grip alignment measured against it) is untouched.
      className="relative my-[3px]"
      data-testid={`draggable-zone-${zoneKey}`}
    >
      <DigitalClock
        time={city ? getTimeInCityZone(baseTime, city.offset) : baseTime}
        cityName={city ? formatCityDisplay(city) : zoneKey}
        cityShortName={city ? city.name : zoneKey}
        timezone={city?.gmtLabel || ""}
        isSelectable
        selectedZoneKey={zoneKey}
        onZoneChange={(newZone) => onZoneChange(index, newZone)}
        isNew={isNew}
        isHighlighted={isHighlighted}
        isDraggable={!isSelectMode}
        isBeingDragged={isDragging}
        zoneKey={zoneKey}
        onTimeUpdate={onTimeUpdate}
        onRemove={onRemove ? () => onRemove(zoneKey) : undefined}
        onShare={onShare}
        isSelectMode={isSelectMode}
        isSelected={isSelected}
        onToggleSelect={onToggleSelect}
        isDragActive={isDragActive}
        dragHandleListeners={listeners}
        heroDate={heroDate}
        isCustomMode={isCustomMode}
        use24Hour={use24Hour}
        relativeOffset={showRelativeTime ? (city?.offset ?? 0) - heroOffset : undefined}
      />
    </div>
  );
}

/** Exported because the incoming-share merge in world-clock.tsx caps against the same
 *  limit — it previously hardcoded a bare `16`, which could drift from this one. */
export const MAX_CLOCKS = 16;
const STORAGE_KEY = "world-happyhour-zones";
// One-time onboarding headline. Absent flag + a returning user's saved zones both
// count as "already onboarded", so only a genuinely new visitor sees the tagline.
const ONBOARDED_KEY = "world-happyhour-onboarded";

function detectLocalCity(): string {
  try {
    const localTz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    const match = getAllCities().find(c => c.timezone === localTz);
    return match?.key || "london_GB";
  } catch {
    return "london_GB";
  }
}

function migrateOldKeys(keys: string[]): string[] {
  const oldToNew: Record<string, string> = {
    "paris": "paris_FR",
    "newYork": "newYorkCity_US",
    "losAngeles": "losAngeles_US",
    "london": "london_GB",
    "tokyo": "tokyo_JP",
    "sydney": "sydney_AU",
    "dubai": "dubai_AE",
    "singapore": "singapore_SG",
    "hongKong": "hongKong_HK",
    "berlin": "berlin_DE",
    "moscow": "moscow_RU",
    "mumbai": "mumbai_IN",
    "shanghai": "shanghai_CN",
    "beijing": "beijing_CN",
    "seoul": "seoul_KR",
    "bangkok": "bangkok_TH",
    "cairo": "cairo_EG",
    "istanbul": "istanbul_TR",
  };

  // Fix keys that were incorrectly migrated in a previous version
  const brokenKeys: Record<string, string> = {
    "newYork_US": "newYorkCity_US",
  };

  const migrated = keys.map(key => {
    if (brokenKeys[key]) return brokenKeys[key];
    if (key.includes("_")) return key;
    return oldToNew[key] || key;
  });
  // Only filter invalid keys if city data is loaded; otherwise keep all keys
  // so we don't wipe the user's zones before data arrives
  if (!areCitiesLoaded()) return migrated;
  return migrated.filter(key => getCityByKey(key) !== undefined);
}

// New visitors start with an empty board — pre-seeding cities they never asked for is disorienting
// (2026-07-19). An empty stored array is honored as-is (no re-seeding), so a user who removes every
// clock stays at zero rather than silently getting defaults back on the next load.
export function initZonesFromStorage(): string[] {
  const stored = localStorage.getItem(STORAGE_KEY);
  if (!stored) return [];
  try {
    return migrateOldKeys(JSON.parse(stored));
  } catch {
    return [];
  }
}

export function TimeZoneConverter({ isCustomMode, selectedTime, onTimeUpdate, onReset, use24Hour, sortEastToWest, onSortEastToWestChange, showRelativeTime, selectedZones, onZonesChange, onGeoDeniedChange, onShareModeChange, highlightedZones, onClockAdded }: TimeZoneConverterProps) {
  const [currentTime, setCurrentTime] = useState<Date | null>(null);
  const [heroZone, setHeroZone] = useState<string>("london_GB");
  const [newlyAddedZone, setNewlyAddedZone] = useState<string | null>(null);
  const [highlightedZone, setHighlightedZone] = useState<string | null>(null);
  // Onboarding tagline. `onboarded` is the source of truth (drives mount);
  // `taglineHiding` is the transient fade+collapse animation state.
  const [onboarded, setOnboarded] = useState<boolean>(() => {
    try {
      return (
        localStorage.getItem(ONBOARDED_KEY) === "1" ||
        localStorage.getItem(STORAGE_KEY) !== null
      );
    } catch {
      return true; // storage blocked → don't nag; treat as onboarded
    }
  });
  const [taglineHiding, setTaglineHiding] = useState(false);
  const [activeId, setActiveId] = useState<string | null>(null);
  const preSortOrderRef = useRef<string[] | null>(null);

  // Mobile drag policy (2026-04-23): on touch devices, drag only activates from
  // the grip-handle icon. The tile-body long-press sensor is unreliable on iOS
  // because Safari commits to a scroll gesture during the 500ms hold and won't
  // release it mid-touch. Desktop (fine pointer) keeps both paths — the mouse
  // sensor covers the tile body naturally.
  const isTouchDevice = useMemo(
    () => typeof window !== "undefined" && window.matchMedia("(pointer: coarse)").matches,
    []
  );
  const tileSensor = useSensor(TileTouchSensor, {
    activationConstraint: { delay: 500, tolerance: 5 },
  });

  const sensors = useSensors(
    useSensor(HandleTouchSensor, {
      activationConstraint: {
        delay: 150,
        tolerance: 8,
      },
    }),
    isTouchDevice ? null : tileSensor,
    useSensor(DesktopMouseSensor, {
      activationConstraint: {
        distance: 8,
      },
    }),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  );

  const [citiesLoaded, setCitiesLoaded] = useState(areCitiesLoaded());
  const [fullLoadFailed, setFullLoadFailed] = useState(didFullCitiesFail());

  // ---- Share flow: select-mode state ----
  const [shareMode, setShareMode] = useState(false);
  const [shareSelection, setShareSelection] = useState<Set<string>>(() => new Set());
  const [includeLocal, setIncludeLocal] = useState(false);
  // Read once, not per render: a browser doesn't grow a share sheet mid-session, and the bar's
  // shape shouldn't depend on when React happens to re-render.
  const [canNativeShare] = useState(
    () => typeof navigator !== "undefined" && typeof navigator.share === "function"
  );
  // Copy Link confirms inline by swapping its own label to "Copied" for a beat, rather than firing a
  // toast — the confirmation belongs on the control the user just pressed. Timer ref so the label
  // restores after 3s and can't outlive the component.
  const [linkCopied, setLinkCopied] = useState(false);
  const copiedTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => () => { if (copiedTimer.current) clearTimeout(copiedTimer.current); }, []);

  const enterShareMode = useCallback((seedKey: string) => {
    setShareSelection(new Set([seedKey]));
    setIncludeLocal(false);
    setLinkCopied(false);
    setShareMode(true);
    track("share_started");
  }, []);

  const toggleShareSelection = useCallback((zoneKey: string) => {
    setShareSelection((prev) => {
      const next = new Set(prev);
      if (next.has(zoneKey)) next.delete(zoneKey);
      else next.add(zoneKey);
      return next;
    });
  }, []);

  const cancelShareMode = useCallback(() => {
    setShareMode(false);
    setShareSelection(new Set());
    setIncludeLocal(false);
  }, []);

  // Report select-mode up to the page so it can gray out the drawer toggle (a sibling above us).
  useEffect(() => {
    onShareModeChange?.(shareMode);
  }, [shareMode, onShareModeChange]);

  // Esc exits select mode (matches the bottom bar's Cancel).
  useEffect(() => {
    if (!shareMode) return;
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape") cancelShareMode();
    }
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [shareMode, cancelShareMode]);

  // (Footer clearance while the bar is up is reserved by CommitBar itself, on mount.)

  // Effective share set: selected grid tiles in grid order, optionally prefixed with the
  // local (hero) city. Deduped so a hero that's also a selected tile counts once.
  const shareKeys = useMemo(() => {
    const selected = selectedZones.filter((z) => shareSelection.has(z));
    return includeLocal ? [heroZone, ...selected.filter((z) => z !== heroZone)] : selected;
  }, [selectedZones, shareSelection, includeLocal, heroZone]);

  const buildShareUrl = useCallback(() => {
    const params = new URLSearchParams();
    params.set("z", shareKeys.join(","));
    // Freeze the moment only when a custom time is active; a real-time share stays live.
    if (isCustomMode && selectedTime) params.set("t", String(selectedTime.getTime()));
    return `${window.location.origin}/?${params.toString()}`;
  }, [shareKeys, isCustomMode, selectedTime]);

  /** Hand the link to the OS share sheet. Only reachable where `navigator.share` exists — the bar
   *  hides Share otherwise rather than quietly turning it into a second Copy Link. */
  const commitShare = useCallback(async () => {
    if (shareKeys.length === 0) return;
    const url = buildShareUrl();
    // Fires before the sheet resolves: this counts intent, and a cancelled sheet is
    // indistinguishable from a completed one anyway (the Web Share API doesn't say).
    track("share_committed", { count: shareKeys.length, method: "native" });
    try {
      await navigator.share!({ url });
    } catch {
      /* native share sheet cancelled — nothing to do */
    }
    // The bar stays put after the sheet closes: the user may want to copy the link too, or share
    // again, and yanking the selection out from under them the moment the OS sheet dismisses is
    // exactly the kind of instability this round is removing.
  }, [shareKeys, buildShareUrl]);

  const copyShareLink = useCallback(async () => {
    if (shareKeys.length === 0) return;
    const url = buildShareUrl();
    track("share_committed", { count: shareKeys.length, method: "copy" });
    try {
      await navigator.clipboard.writeText(url);
    } catch {
      /* clipboard blocked (insecure context, or permission denied) — leave select mode intact
         so the selection isn't silently lost with nothing to show for it. */
      return;
    }
    // Inline "Copied" on the button, and the bar stays up — copying a link isn't committing the
    // share, so the selection shouldn't be torn down.
    setLinkCopied(true);
    if (copiedTimer.current) clearTimeout(copiedTimer.current);
    copiedTimer.current = setTimeout(() => setLinkCopied(false), 3000);
  }, [shareKeys, buildShareUrl]);

  // Three-tier load: top (fast, inline bundle) → cache fallback → full (lazy).
  useEffect(() => {
    loadTopCities().then(() => {
      const tzFallback = detectLocalCity();
      setHeroZone(tzFallback);
      // Upgrade the hero clock to the geographically-closest city once geolocation resolves.
      // On denial we keep the timezone-derived fallback and surface a notice in the footer.
      resolveLocalCity(tzFallback).then(({ key, geoDenied: denied }) => {
        setHeroZone((current) => (current === tzFallback ? key : current));
        if (denied) onGeoDeniedChange?.(true);
      });
    });

    // Kick off full-dataset load during browser idle time so the Add Time Zone
    // dropdown has every city ready before most users think to open it.
    const w = window as Window & {
      requestIdleCallback?: (cb: () => void, opts?: { timeout: number }) => number;
      cancelIdleCallback?: (handle: number) => void;
    };
    let idleHandle: number | undefined;
    let timeoutHandle: number | undefined;
    const startFullLoad = () => {
      loadCities()
        .then(() => setCitiesLoaded(true))
        .catch(() => setFullLoadFailed(true));
    };
    if (w.requestIdleCallback) {
      idleHandle = w.requestIdleCallback(startFullLoad, { timeout: 3000 });
    } else {
      timeoutHandle = window.setTimeout(startFullLoad, 1500);
    }
    return () => {
      if (idleHandle !== undefined && w.cancelIdleCallback) w.cancelIdleCallback(idleHandle);
      if (timeoutHandle !== undefined) window.clearTimeout(timeoutHandle);
    };
  }, []);

  // Sort zones east-to-west when toggled on; restore original order when toggled off
  useEffect(() => {
    if (sortEastToWest) {
      // Snapshot current manual order before sorting
      onZonesChange((prev) => {
        preSortOrderRef.current = [...prev];
        const sorted = [...prev].sort((a, b) => {
          const cityA = getCityOrCachedTile(a);
          const cityB = getCityOrCachedTile(b);
          return (cityB?.offset ?? 0) - (cityA?.offset ?? 0);
        });
        if (sorted.every((z, i) => z === prev[i])) return prev;
        return sorted;
      });
    } else if (preSortOrderRef.current) {
      // Restore pre-sort order, accounting for zones added/removed since
      const snapshot = preSortOrderRef.current;
      onZonesChange((current) => {
        const currentSet = new Set(current);
        const restored = snapshot.filter((z) => currentSet.has(z));
        const added = current.filter((z) => !snapshot.includes(z));
        return [...restored, ...added];
      });
      preSortOrderRef.current = null;
    }
  }, [sortEastToWest]);

  useEffect(() => {
    if (isCustomMode) return;
    // Pause clock tick during drag — prevents re-renders that cancel touch sensor activation
    if (activeId !== null) return;

    setCurrentTime(new Date());

    const interval = setInterval(() => {
      // Mark as low-priority so React won't interrupt scroll gestures to run this
      startTransition(() => {
        setCurrentTime(new Date());
      });
    }, 1000);

    return () => clearInterval(interval);
  }, [isCustomMode, activeId]);

  // Force-refresh time when the tab resumes from background: some browsers throttle
  // setInterval aggressively (or discard the tab), leaving the clock stuck on stale data.
  useEffect(() => {
    if (isCustomMode) return;
    function refreshNow() {
      if (document.visibilityState === "visible") {
        setCurrentTime(new Date());
      }
    }
    document.addEventListener("visibilitychange", refreshNow);
    window.addEventListener("focus", refreshNow);
    return () => {
      document.removeEventListener("visibilitychange", refreshNow);
      window.removeEventListener("focus", refreshNow);
    };
  }, [isCustomMode]);

  const handleZoneChange = useCallback((index: number, zoneKey: string) => {
    // If the picked city is already displayed on another tile, leave this tile
    // unchanged and flash the existing tile — mirrors the add-dropdown behavior
    // at lines 608-623. Prevents the prior swap-and-stale-edit-state bug.
    const existingIndex = selectedZones.indexOf(zoneKey);
    if (existingIndex !== -1 && existingIndex !== index) {
      setHighlightedZone(zoneKey);
      setTimeout(() => setHighlightedZone(null), 1500);
      return;
    }
    onZonesChange((prev: string[]) => {
      const newZones = [...prev];
      newZones[index] = zoneKey;
      return newZones;
    });
  }, [onZonesChange, selectedZones]);

  const handleAddClock = useCallback((zoneKey: string) => {
    if (selectedZones.length >= MAX_CLOCKS) return;
    if (selectedZones.includes(zoneKey)) return;

    // Manual add invalidates sort — clear snapshot and disable toggle
    if (sortEastToWest) {
      preSortOrderRef.current = null;
      onSortEastToWestChange(false);
    }

    onZonesChange((prev: string[]) => [zoneKey, ...prev]);
    setNewlyAddedZone(zoneKey);
    track("city_added", { city_key: zoneKey });
    onClockAdded?.();

    // First-ever add dismisses the onboarding tagline, once and for all.
    if (!onboarded) {
      try { localStorage.setItem(ONBOARDED_KEY, "1"); } catch { /* storage blocked */ }
      const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
      // Reduced motion skips the transition entirely, so onTransitionEnd never
      // fires — cut straight to unmount instead of animating.
      if (reduce) setOnboarded(true);
      else setTaglineHiding(true);
    }

    setTimeout(() => {
      setNewlyAddedZone(null);
    }, 1500);
  }, [selectedZones, onZonesChange, sortEastToWest, onSortEastToWestChange, onboarded, onClockAdded]);

  // Unmount the tagline only after the height collapse finishes (the opacity
  // fade transitionend fires first and must be ignored).
  const handleTaglineCollapsed = useCallback((e: { propertyName: string }) => {
    if (e.propertyName === "grid-template-rows") setOnboarded(true);
  }, []);

  const handleRemoveClock = useCallback((zoneKey: string) => {
    // Last-tile guard: never allow the grid to go empty.
    onZonesChange((prev: string[]) => {
      if (prev.length <= 1) return prev;
      track("city_removed", { city_key: zoneKey });
      return prev.filter((z: string) => z !== zoneKey);
    });
  }, [onZonesChange]);

  const [addZoneOpen, setAddZoneOpen] = useState(false);
  const [addZoneSearchQuery, setAddZoneSearchQuery] = useState("");
  const addZoneRef = useRef<HTMLDivElement>(null);

  // Opening the dropdown nudges the full-dataset load if idle didn't fire yet.
  useEffect(() => {
    if (addZoneOpen) {
      loadCities()
        .then(() => setCitiesLoaded(true))
        .catch(() => setFullLoadFailed(true));
    }
  }, [addZoneOpen]);

  // Keep the tile-metadata cache warm so returning users render tiles on first paint.
  useEffect(() => {
    if (!areSearchCitiesReady()) return;
    const cities: TimezoneOption[] = [];
    for (const key of selectedZones) {
      const c = getCityByKey(key);
      if (c) cities.push(c);
    }
    const hero = getCityByKey(heroZone);
    if (hero) cities.push(hero);
    if (cities.length > 0) cacheTileMetadata(cities);
  }, [selectedZones, heroZone, citiesLoaded]);

  // Close dropdown when clicking outside
  useEffect(() => {
    if (!addZoneOpen) return;
    function handleClickOutside(e: MouseEvent) {
      if (addZoneRef.current && !addZoneRef.current.contains(e.target as Node)) {
        setAddZoneOpen(false);
        setAddZoneSearchQuery("");
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [addZoneOpen]);

  const allFilteredCities = searchCities(addZoneSearchQuery, 100);

  const canAddMoreZones = selectedZones.length < MAX_CLOCKS;

  function handleDragStart(event: DragStartEvent) {
    setActiveId(event.active.id as string);
    // Prevent page scroll fighting the drag gesture on mobile
    document.body.style.overflow = "hidden";
    document.body.style.touchAction = "none";
  }

  function handleDragEnd(event: DragEndEvent) {
    const { active, over } = event;

    setActiveId(null);
    document.body.style.overflow = "";
    document.body.style.touchAction = "";

    if (over && active.id !== over.id) {
      // Manual reorder invalidates the sort — clear snapshot and disable toggle
      if (sortEastToWest) {
        preSortOrderRef.current = null;
        onSortEastToWestChange(false);
      }
      onZonesChange((items) => {
        const oldIndex = items.indexOf(active.id as string);
        const newIndex = items.indexOf(over.id as string);
        return arrayMove(items, oldIndex, newIndex);
      });
    }
  }

  function handleDragCancel(_event: DragCancelEvent) {
    setActiveId(null);
    document.body.style.overflow = "";
    document.body.style.touchAction = "";
  }

  // Stabilize zones reference so SortableContext doesn't re-initialize
  // when cloud sync or other updates create a new array with identical
  // contents — which would cancel pending touch sensor activations
  const prevZonesRef = useRef(selectedZones);
  const stableZones = useMemo(() => {
    const prev = prevZonesRef.current;
    if (prev.length === selectedZones.length && prev.every((z, i) => z === selectedZones[i])) {
      return prev;
    }
    prevZonesRef.current = selectedZones;
    return selectedZones;
  }, [selectedZones]);

  function getBaseTime(): Date {
    if (isCustomMode && selectedTime) {
      return selectedTime;
    }
    return currentTime || new Date();
  }

  if (!areSearchCitiesReady() || (!currentTime && !isCustomMode)) {
    const heroCity = getCityOrCachedTile(heroZone);
    return (
      // Skeleton mirrors the loaded layout's rule placement — the rule belongs to the hero
      // block, not the city list. Getting this wrong flashes two rules during load.
      <div>
        <section className="sticky top-0 z-40 bg-background border-b border-border pb-16">
          <p className="text-sm font-medium uppercase tracking-wide text-muted-foreground">
            {heroCity ? heroCity.name : heroZone}
          </p>
          <p className="mt-1 font-display text-6xl font-black tracking-tight text-foreground md:text-8xl">
            --:--:--
          </p>
          <p className="mt-2 text-sm text-muted-foreground">{heroCity?.gmtLabel}</p>
        </section>

        <section className="pt-12">
          <div className="mb-8">
            <span className="text-sm text-muted-foreground">Loading...</span>
          </div>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 sm:gap-8">
            {selectedZones.map((zoneKey) => {
              const city = getCityOrCachedTile(zoneKey);
              return (
                <div key={zoneKey}>
                  <p className="text-sm font-medium uppercase tracking-wide text-muted-foreground">
                    {city ? formatCityDisplay(city) : zoneKey}
                  </p>
                  <p className="mt-1 font-display text-3xl font-black tracking-tight text-foreground md:text-4xl">
                    --:--
                  </p>
                  <p className="mt-1 text-xs text-muted-foreground">{city?.gmtLabel}</p>
                </div>
              );
            })}
          </div>
        </section>
      </div>
    );
  }

  const baseTime = getBaseTime();
  const heroCity = getCityOrCachedTile(heroZone);
  const heroTime = heroCity ? getTimeInCityZone(baseTime, heroCity.offset) : baseTime;
  const heroOffset = heroCity?.offset ?? 0;
  const activeCity = activeId ? getCityOrCachedTile(activeId) : null;

  return (
    <div>
      {/* The hero and its rule are one sticky unit (Figma 329:3521). The logo bar scrolls away
          above it; this block locks to the top of the viewport and the tiles scroll underneath,
          which is what bg-background is for — without it they'd show through.
          z-40 keeps it below the fixed menu layer (z-55) and the sidebar panel (z-70).
          .hero-sticky supplies the padding-bottom that collapses 64px → 0, so the rule rides up
          to meet the hero as you scroll. */}
      <section className="hero-sticky sticky top-0 z-40 bg-background border-b border-border">
        <DigitalClock
          time={heroTime}
          cityName={heroCity ? heroCity.name : heroZone}
          timezone={heroCity?.gmtLabel || ""}
          isHero
          showSeconds={!isCustomMode}
          zoneKey={heroZone}
          onTimeUpdate={onTimeUpdate}
          isCustomMode={isCustomMode}
          onReset={onReset}
          use24Hour={use24Hour}
        />
      </section>

      <section className="pt-[25px] sm:pt-6">
        {!onboarded && (
          // Grid whose single row animates 1fr→0fr; the overflow-hidden child
          // collapses to zero height and the button + tile grid below slide up
          // in normal flow. Opacity fades first (short), then the row collapses
          // (longer, delayed) — "quickly fade, then elegantly animate up".
          <div
            onTransitionEnd={handleTaglineCollapsed}
            className={`grid overflow-hidden ease-out transition-[opacity,grid-template-rows] [transition-duration:180ms,360ms] [transition-delay:0ms,150ms] motion-reduce:transition-none ${
              taglineHiding ? "grid-rows-[0fr] opacity-0" : "grid-rows-[1fr] opacity-100"
            }`}
          >
            <div className="min-h-0 overflow-hidden px-[10px] pb-[32px]">
              <h2 className="w-full sm:w-3/5 font-display font-black text-foreground text-[36px] leading-[38px] tracking-[-1px]">
                Track clocks and convert time zones for up to sixteen cities
              </h2>
            </div>
          </div>
        )}
        <div className="mb-[25px] sm:mb-8 relative" ref={addZoneRef}>
          <div className="flex items-center gap-[5px] px-[10px] pb-[20px]">
            <button
              className="flex items-center gap-1 text-sm font-medium uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors focus:outline-none disabled:opacity-40 disabled:hover:text-muted-foreground"
              disabled={!canAddMoreZones || shareMode}
              onClick={() => {
                if (shareMode) return;
                setAddZoneOpen(!addZoneOpen);
                if (addZoneOpen) setAddZoneSearchQuery("");
              }}
              data-testid="button-add-timezone"
            >
              Add Clock
              <ChevronsUpDown className="h-3 w-3 opacity-50" />
            </button>
          </div>
          {addZoneOpen && (
            <div className="absolute left-0 right-0 z-50 rounded-[8px] border border-[#e5e7eb] dark:border-[#6C6C6C] bg-white dark:bg-background shadow-[0px_4px_6px_-1px_rgba(0,0,0,0.1),0px_2px_4px_-2px_rgba(0,0,0,0.1)] overflow-clip">
              <Command shouldFilter={false}>
                <CommandInput
                  placeholder="Search cities..."
                  value={addZoneSearchQuery}
                  onValueChange={setAddZoneSearchQuery}
                  onKeyDown={(e) => {
                    if (e.key === " ") {
                      e.stopPropagation();
                    }
                  }}
                  autoFocus
                  data-testid="input-add-zone-search"
                />
                <CommandList>
                  <CommandEmpty>Can’t find “{addZoneSearchQuery}”</CommandEmpty>
                  <CommandGroup>
                    {allFilteredCities.map((city) => {
                      const isDisplayed = selectedZones.includes(city.key);
                      return (
                        <CommandItem
                          key={city.key}
                          value={city.key}
                          onSelect={() => {
                            if (isDisplayed) {
                              // Close menu, scroll to tile, highlight it
                              setAddZoneOpen(false);
                              setAddZoneSearchQuery("");
                              setHighlightedZone(city.key);
                              setTimeout(() => {
                                const el = document.querySelector(`[data-testid="clock-tile-${city.key}"]`);
                                el?.scrollIntoView({ behavior: "smooth", block: "center" });
                              }, 100);
                              setTimeout(() => setHighlightedZone(null), 1500);
                            } else {
                              handleAddClock(city.key);
                              setAddZoneOpen(false);
                              setAddZoneSearchQuery("");
                            }
                          }}
                          data-testid={`menu-item-${city.key}`}
                        >
                          <div className="flex flex-col">
                            <span className={isDisplayed ? "font-semibold text-foreground" : ""}>
                              {city.name}
                            </span>
                            <span className="text-xs text-muted-foreground">
                              {formatCityDetail(city)}
                            </span>
                          </div>
                        </CommandItem>
                      );
                    })}
                  </CommandGroup>
                </CommandList>
                {fullLoadFailed && (
                  <p className="border-t border-[#e5e7eb] dark:border-[#6C6C6C] px-[12px] py-[8px] text-[11px] text-muted-foreground">
                    Showing top 500 cities — full list unavailable.
                  </p>
                )}
              </Command>
            </div>
          )}
        </div>

        <DndContext
          sensors={shareMode ? [] : sensors}
          collisionDetection={closestCenter}
          onDragStart={handleDragStart}
          onDragEnd={handleDragEnd}
          onDragCancel={handleDragCancel}
        >
          <SortableContext
            items={stableZones}
            strategy={rectSortingStrategy}
          >
            <div className="grid grid-cols-1 gap-[5px] sm:grid-cols-2 sm:gap-2.5 lg:grid-cols-3">
              {selectedZones.map((zoneKey, index) => (
                <SortableClockItem
                  key={zoneKey}
                  id={zoneKey}
                  zoneKey={zoneKey}
                  index={index}
                  baseTime={baseTime}
                  heroDate={heroTime}
                  isNew={newlyAddedZone === zoneKey}
                  isHighlighted={highlightedZone === zoneKey || !!highlightedZones?.includes(zoneKey)}
                  onZoneChange={handleZoneChange}
                  onTimeUpdate={onTimeUpdate}
                  onRemove={selectedZones.length <= 1 ? undefined : handleRemoveClock}
                  onShare={enterShareMode}
                  isSelectMode={shareMode}
                  isSelected={shareSelection.has(zoneKey)}
                  onToggleSelect={toggleShareSelection}
                  allZones={selectedZones}
                  isDragActive={activeId !== null}
                  isCustomMode={isCustomMode}
                  use24Hour={use24Hour}
                  heroOffset={heroOffset}
                  showRelativeTime={showRelativeTime}
                />
              ))}
            </div>
          </SortableContext>

          <DragOverlay>
            {activeId && activeCity ? (
              <div className="opacity-90">
                <DigitalClock
                  time={getTimeInCityZone(baseTime, activeCity.offset)}
                  cityName={formatCityDisplay(activeCity)}
                  timezone={activeCity.gmtLabel}
                  isSelectable={false}
                  isDraggable
                  isBeingDragged
                  heroDate={heroTime}
                  isCustomMode={isCustomMode}
                  use24Hour={use24Hour}
                  relativeOffset={showRelativeTime ? activeCity.offset - heroOffset : undefined}
                />
              </div>
            ) : null}
          </DragOverlay>
        </DndContext>

      </section>

      {shareMode && (
        <ShareSelectionBar
          count={shareKeys.length}
          includeLocal={includeLocal}
          onToggleIncludeLocal={() => setIncludeLocal((v) => !v)}
          onCancel={cancelShareMode}
          onShare={commitShare}
          onCopyLink={copyShareLink}
          linkCopied={linkCopied}
          canNativeShare={canNativeShare}
        />
      )}
    </div>
  );
}
