// GENERATED — do not edit by hand.
//
// key -> display city name for the top-500 tier, used by functions/lib/preview.ts to name shared
// cities in social previews. Regenerate when client/src/data/cities-top.json changes:
//   node scripts/build-city-names.mjs   (see that script; it replays city-lookup.ts key generation)
//
// Kept as a self-contained module inside functions/ on purpose: the Pages Functions build must not
// depend on a JSON import attribute or a cross-directory import into client/.

export const CITY_NAMES: Record<string, string> = {
  "shanghai_CN": "Shanghai",
  "beijing_CN": "Beijing",
  "shenzhen_CN": "Shenzhen",
  "guangzhou_CN": "Guangzhou",
  "kinshasa_CD": "Kinshasa",
  "istanbul_TR": "Istanbul",
  "lagos_NG": "Lagos",
  "hoChiMinhCity_VN": "Ho Chi Minh City",
  "chengdu_CN": "Chengdu",
  "lahore_PK": "Lahore",
  "mumbai_IN": "Mumbai",
  "saoPaulo_BR": "São Paulo",
  "mexicoCity_MX": "Mexico City",
  "karachi_PK": "Karachi",
  "tianjin_CN": "Tianjin",
  "delhi_IN": "Delhi",
  "wuhan_CN": "Wuhan",
  "moscow_RU": "Moscow",
  "dhaka_BD": "Dhaka",
  "seoul_KR": "Seoul",
  "tokyo_JP": "Tokyo",
  "dongguan_CN": "Dongguan",
  "cairo_EG": "Cairo",
  "xian_CN": "Xi’an",
  "johannesburg_ZA": "Johannesburg",
  "nanjing_CN": "Nanjing",
  "hangzhou_CN": "Hangzhou",
  "foshan_CN": "Foshan",
  "london_GB": "London",
  "newYorkCity_US": "New York City",
  "jakarta_ID": "Jakarta",
  "bengaluru_IN": "Bengaluru",
  "hanoi_VN": "Hanoi",
  "taipei_TW": "Taipei",
  "lima_PE": "Lima",
  "bogota_CO": "Bogotá",
  "chongqing_CN": "Chongqing",
  "hongKong_HK": "Hong Kong",
  "baghdad_IQ": "Baghdad",
  "qingdao_CN": "Qingdao",
  "tehran_IR": "Tehran",
  "shenyang_CN": "Shenyang",
  "hyderabad_IN": "Hyderabad",
  "riodeJaneiro_BR": "Rio de Janeiro",
  "suzhou_CN": "Suzhou",
  "ahmedabad_IN": "Ahmedabad",
  "abidjan_CI": "Abidjan",
  "singapore_SG": "Singapore",
  "sydney_AU": "Sydney",
  "daresSalaam_TZ": "Dar es Salaam",
  "saintPetersburg_RU": "Saint Petersburg",
  "melbourne_AU": "Melbourne",
  "alexandria_EG": "Alexandria",
  "harbin_CN": "Harbin",
  "bangkok_TH": "Bangkok",
  "hefei_CN": "Hefei",
  "dalian_CN": "Dalian",
  "kano_NG": "Kano",
  "santiago_CL": "Santiago",
  "capeTown_ZA": "Cape Town",
  "peshawar_PK": "Peshawar",
  "changchun_CN": "Changchun",
  "jeddah_SA": "Jeddah",
  "chennai_IN": "Chennai",
  "kolkata_IN": "Kolkata",
  "xiamen_CN": "Xiamen",
  "surat_IN": "Surat",
  "yangon_MM": "Yangon",
  "baoan_CN": "Bao'an",
  "kabul_AF": "Kabul",
  "nairobi_KE": "Nairobi",
  "wuxi_CN": "Wuxi",
  "giza_EG": "Giza",
  "jinan_CN": "Jinan",
  "taiyuan_CN": "Taiyuan",
  "zhengzhou_CN": "Zhengzhou",
  "bamako_ML": "Bamako",
  "riyadh_SA": "Riyadh",
  "newTaipeiCity_TW": "New Taipei City",
  "shijiazhuang_CN": "Shijiazhuang",
  "chattogram_BD": "Chattogram",
  "addisAbaba_ET": "Addis Ababa",
  "kunming_CN": "Kunming",
  "zhongshan_CN": "Zhongshan",
  "nanning_CN": "Nanning",
  "shantou_CN": "Shantou",
  "losAngeles_US": "Los Angeles",
  "faisalabad_PK": "Faisalabad",
  "dubai_AE": "Dubai",
  "yokohama_JP": "Yokohama",
  "fuzhou_CN": "Fuzhou",
  "ningbo_CN": "Ningbo",
  "casablanca_MA": "Casablanca",
  "ibadan_NG": "Ibadan",
  "puyang_CN": "Puyang",
  "ankara_TR": "Ankara",
  "shiyan_CN": "Shiyan",
  "berlin_DE": "Berlin",
  "tangshan_CN": "Tangshan",
  "rawalpindi_PK": "Rawalpindi",
  "lueliang_CN": "Lüliang",
  "busan_KR": "Busan",
  "durban_ZA": "Durban",
  "changzhou_CN": "Changzhou",
  "madrid_ES": "Madrid",
  "pyongyang_KP": "Pyongyang",
  "zibo_CN": "Zibo",
  "pune_IN": "Pune",
  "bursa_TR": "Bursa",
  "changsha_CN": "Changsha",
  "quezonCity_PH": "Quezon City",
  "jaipur_IN": "Jaipur",
  "incheon_KR": "Incheon",
  "guiyang_CN": "Guiyang",
  "uEruemqi_CN": "Ürümqi",
  "lanzhou_CN": "Lanzhou",
  "caracas_VE": "Caracas",
  "izmir_TR": "İzmir",
  "huizhou_CN": "Huizhou",
  "buenosAires_AR": "Buenos Aires",
  "surabaya_ID": "Surabaya",
  "haikou_CN": "Haikou",
  "taichung_TW": "Taichung",
  "kanpur_IN": "Kanpur",
  "kyiv_UA": "Kyiv",
  "toronto_CA": "Toronto",
  "quito_EC": "Quito",
  "brisbane_AU": "Brisbane",
  "luanda_AO": "Luanda",
  "osaka_JP": "Osaka",
  "linyi_CN": "Linyi",
  "baoding_CN": "Baoding",
  "kaohsiung_TW": "Kaohsiung",
  "brooklyn_US": "Brooklyn",
  "guayaquil_EC": "Guayaquil",
  "beloHorizonte_BR": "Belo Horizonte",
  "salvador_BR": "Salvador",
  "abuja_NG": "Abuja",
  "gazipur_BD": "Gazipur",
  "chicago_US": "Chicago",
  "wenzhou_CN": "Wenzhou",
  "dakar_SN": "Dakar",
  "haiphong_VN": "Haiphong",
  "yunfu_CN": "Yunfu",
  "mogadishu_SO": "Mogadishu",
  "bekasi_ID": "Bekasi",
  "kumasi_GH": "Kumasi",
  "gujranwala_PK": "Gujranwala",
  "huaian_CN": "Huai'an",
  "lucknow_IN": "Lucknow",
  "bandung_ID": "Bandung",
  "medan_ID": "Medan",
  "ouagadougou_BF": "Ouagadougou",
  "nagpur_IN": "Nagpur",
  "fortaleza_BR": "Fortaleza",
  "cali_CO": "Cali",
  "daegu_KR": "Daegu",
  "algiers_DZ": "Algiers",
  "nanchang_CN": "Nanchang",
  "hohhot_CN": "Hohhot",
  "nagoya_JP": "Nagoya",
  "rome_IT": "Rome",
  "queens_US": "Queens",
  "houston_US": "Houston",
  "perth_AU": "Perth",
  "mashhad_IR": "Mashhad",
  "shaoxing_CN": "Shaoxing",
  "nantong_CN": "Nantong",
  "yantai_CN": "Yantai",
  "lubumbashi_CD": "Lubumbashi",
  "manaus_BR": "Manaus",
  "lusaka_ZM": "Lusaka",
  "brasilia_BR": "Brasília",
  "zhuhai_CN": "Zhuhai",
  "santoDomingo_DO": "Santo Domingo",
  "lome_TG": "Lomé",
  "multan_PK": "Multan",
  "havana_CU": "Havana",
  "baotou_CN": "Baotou",
  "depok_ID": "Depok",
  "paris_FR": "Paris",
  "coimbatore_IN": "Coimbatore",
  "gaziantep_TR": "Gaziantep",
  "qingyang_CN": "Qingyang",
  "portHarcourt_NG": "Port Harcourt",
  "pretoria_ZA": "Pretoria",
  "cordoba_AR": "Córdoba",
  "mbujiMayi_CD": "Mbuji-Mayi",
  "aleppo_SY": "Aleppo",
  "kunshan_CN": "Kunshan",
  "weifang_CN": "Weifang",
  "zunyi_CN": "Zunyi",
  "laPaz_BO": "La Paz",
  "lianyungang_CN": "Lianyungang",
  "medellin_CO": "Medellín",
  "indore_IN": "Indore",
  "brazzaville_CG": "Brazzaville",
  "tashkent_UZ": "Tashkent",
  "ganzhou_CN": "Ganzhou",
  "almaty_KZ": "Almaty",
  "khartoum_SD": "Khartoum",
  "sapporo_JP": "Sapporo",
  "accra_GH": "Accra",
  "curitiba_BR": "Curitiba",
  "ordos_CN": "Ordos",
  "sanaa_YE": "Sanaa",
  "conakry_GN": "Conakry",
  "tijuana_MX": "Tijuana",
  "hyderabad_PK": "Hyderabad",
  "beirut_LB": "Beirut",
  "tangerang_ID": "Tangerang",
  "jieyang_CN": "Jieyang",
  "jilin_CN": "Jilin",
  "bucharest_RO": "Bucharest",
  "camayenne_GN": "Camayenne",
  "kakamega_KE": "Kakamega",
  "nanchong_CN": "Nanchong",
  "tainan_TW": "Tainan",
  "datong_CN": "Datong",
  "kaduna_NG": "Kaduna",
  "omdurman_SD": "Omdurman",
  "davao_PH": "Davao",
  "hamburg_DE": "Hamburg",
  "thane_IN": "Thāne",
  "iztapalapa_MX": "Iztapalapa",
  "santaCruzdelaSierra_BO": "Santa Cruz de la Sierra",
  "vadodara_IN": "Vadodara",
  "adana_TR": "Adana",
  "nanyang_CN": "Nanyang",
  "abuDhabi_AE": "Abu Dhabi",
  "sharjah_AE": "Sharjah",
  "bhopal_IN": "Bhopal",
  "jiangmen_CN": "Jiangmen",
  "diyarbakir_TR": "Diyarbakır",
  "beninCity_NG": "Benin City",
  "jiangyin_CN": "Jiangyin",
  "fuyang_CN": "Fuyang",
  "montreal_CA": "Montréal",
  "bayanNur_CN": "Bayan Nur",
  "maracaibo_VE": "Maracaibo",
  "chaozhou_CN": "Chaozhou",
  "minsk_BY": "Minsk",
  "budapest_HU": "Budapest",
  "qingyuan_CN": "Qingyuan",
  "taian_CN": "Tai’an",
  "rasapudipalem_IN": "Rasapūdipalem",
  "pimpriChinchwad_IN": "Pimpri-Chinchwad",
  "caloocan_PH": "Caloocan",
  "warsaw_PL": "Warsaw",
  "soweto_ZA": "Soweto",
  "puebla_MX": "Puebla",
  "vienna_AT": "Vienna",
  "barcelona_ES": "Barcelona",
  "patna_IN": "Patna",
  "mosul_IQ": "Mosul",
  "kallakurichi_IN": "Kallakurichi",
  "kampala_UG": "Kampala",
  "xining_CN": "Xining",
  "changshu_CN": "Changshu",
  "palembang_ID": "Palembang",
  "huainan_CN": "Huainan",
  "rabat_MA": "Rabat",
  "semarang_ID": "Semarang",
  "recife_BR": "Recife",
  "phoenix_US": "Phoenix",
  "ecatepecdeMorelos_MX": "Ecatepec de Morelos",
  "luan_CN": "Lu’an",
  "valencia_VE": "Valencia",
  "ludhiana_IN": "Ludhiana",
  "yancheng_CN": "Yancheng",
  "novosibirsk_RU": "Novosibirsk",
  "erbil_IQ": "Erbil",
  "fukuoka_JP": "Fukuoka",
  "taizhou_CN": "Taizhou",
  "daqing_CN": "Daqing",
  "manila_PH": "Manila",
  "wuhu_CN": "Wuhu",
  "santiagodeQueretaro_MX": "Santiago de Querétaro",
  "dazhou_CN": "Dazhou",
  "yangzhou_CN": "Yangzhou",
  "leondelosAldama_MX": "León de los Aldama",
  "makkah_SA": "Makkah",
  "philadelphia_US": "Philadelphia",
  "phnomPenh_KH": "Phnom Penh",
  "guilin_CN": "Guilin",
  "damascus_SY": "Damascus",
  "quetta_PK": "Quetta",
  "zhaoqing_CN": "Zhaoqing",
  "onitsha_NG": "Onitsha",
  "mianyang_CN": "Mianyang",
  "isfahan_IR": "Isfahan",
  "wanzhou_CN": "Wanzhou",
  "harare_ZW": "Harare",
  "monrovia_LR": "Monrovia",
  "putian_CN": "Putian",
  "kawasaki_JP": "Kawasaki",
  "shangqiu_CN": "Shangqiu",
  "goiania_BR": "Goiânia",
  "auckland_NZ": "Auckland",
  "sanAntonio_US": "San Antonio",
  "kobe_JP": "Kobe",
  "stockholm_SE": "Stockholm",
  "ciudadJuarez_MX": "Ciudad Juárez",
  "canTho_VN": "Cần Thơ",
  "khulna_BD": "Khulna",
  "belem_BR": "Belém",
  "yekaterinburg_RU": "Yekaterinburg",
  "portoAlegre_BR": "Porto Alegre",
  "yinchuan_CN": "Yinchuan",
  "manhattan_US": "Manhattan",
  "nashik_IN": "Nashik",
  "asuncion_PY": "Asunción",
  "yiwu_CN": "Yiwu",
  "zapopan_MX": "Zapopan",
  "daejeon_KR": "Daejeon",
  "adelaide_AU": "Adelaide",
  "quanzhou_CN": "Quanzhou",
  "madurai_IN": "Madurai",
  "jinhua_CN": "Jinhua",
  "kyoto_JP": "Kyoto",
  "cixi_CN": "Cixi",
  "changde_CN": "Changde",
  "kualaLumpur_MY": "Kuala Lumpur",
  "kaifeng_CN": "Kaifeng",
  "anshan_CN": "Anshan",
  "karaj_IR": "Karaj",
  "kathmandu_NP": "Kathmandu",
  "baoji_CN": "Baoji",
  "suqian_CN": "Suqian",
  "liuzhou_CN": "Liuzhou",
  "tirunelveli_IN": "Tirunelveli",
  "kayseri_TR": "Kayseri",
  "kharkiv_UA": "Kharkiv",
  "konya_TR": "Konya",
  "zhangjiagang_CN": "Zhangjiagang",
  "agra_IN": "Agra",
  "tabriz_IR": "Tabriz",
  "makassar_ID": "Makassar",
  "jinjiang_CN": "Jinjiang",
  "faridabad_IN": "Faridabad",
  "bozhou_CN": "Bozhou",
  "qujing_CN": "Qujing",
  "southTangerang_ID": "South Tangerang",
  "sanDiego_US": "San Diego",
  "zhanjiang_CN": "Zhanjiang",
  "fushun_CN": "Fushun",
  "gwangju_KR": "Gwangju",
  "rajkot_IN": "Rājkot",
  "luoyang_CN": "Luoyang",
  "guadalajara_MX": "Guadalajara",
  "theBronx_US": "The Bronx",
  "guankou_CN": "Guankou",
  "hue_VN": "Huế",
  "milan_IT": "Milan",
  "najafgarh_IN": "Najafgarh",
  "nDjamena_TD": "N'Djamena",
  "handan_CN": "Handan",
  "bannu_PK": "Bannu",
  "yichang_CN": "Yichang",
  "antananarivo_MG": "Antananarivo",
  "heze_CN": "Heze",
  "antalya_TR": "Antalya",
  "abobo_CI": "Abobo",
  "jamshedpur_IN": "Jamshedpur",
  "douala_CM": "Douala",
  "basrah_IQ": "Basrah",
  "dallas_US": "Dallas",
  "saitama_JP": "Saitama",
  "gorakhpur_IN": "Gorakhpur",
  "niamey_NE": "Niamey",
  "liupanshui_CN": "Liupanshui",
  "taguig_PH": "Taguig",
  "maoming_CN": "Maoming",
  "calgary_CA": "Calgary",
  "tripoli_LY": "Tripoli",
  "callao_PE": "Callao",
  "madinah_SA": "Madinah",
  "yaounde_CM": "Yaoundé",
  "qinzhou_CN": "Qinzhou",
  "luohe_CN": "Luohe",
  "xiangyang_CN": "Xiangyang",
  "yangjiang_CN": "Yangjiang",
  "yixing_CN": "Yixing",
  "pimpri_IN": "Pimpri",
  "daNang_VN": "Da Nang",
  "amman_JO": "Amman",
  "budta_PH": "Budta",
  "belgrade_RS": "Belgrade",
  "bienHoa_VN": "Biên Hòa",
  "montevideo_UY": "Montevideo",
  "xuchang_CN": "Xuchang",
  "kalyan_IN": "Kalyān",
  "zigong_CN": "Zigong",
  "munich_DE": "Munich",
  "nizhniyNovgorod_RU": "Nizhniy Novgorod",
  "jepara_ID": "Jepara",
  "maputo_MZ": "Maputo",
  "xuzhou_CN": "Xuzhou",
  "dammam_SA": "Dammam",
  "neijiang_CN": "Neijiang",
  "shiraz_IR": "Shiraz",
  "heshan_CN": "Heshan",
  "dombivali_IN": "Dombivali",
  "kananga_CD": "Kananga",
  "kazan_RU": "Kazan",
  "jining_CN": "Jining",
  "barquisimeto_VE": "Barquisimeto",
  "shubraalKhaymah_EG": "Shubrā al Khaymah",
  "portauPrince_HT": "Port-au-Prince",
  "xinyang_CN": "Xinyang",
  "liaocheng_CN": "Liaocheng",
  "jinzhong_CN": "Jinzhong",
  "meerut_IN": "Meerut",
  "virar_IN": "Virār",
  "nowrangapur_IN": "Nowrangapur",
  "karbala_IQ": "Karbala",
  "changzhi_CN": "Changzhi",
  "tianshui_CN": "Tianshui",
  "mombasa_KE": "Mombasa",
  "mandalay_MM": "Mandalay",
  "srinagar_IN": "Srinagar",
  "barranquilla_CO": "Barranquilla",
  "chelyabinsk_RU": "Chelyabinsk",
  "merida_MX": "Mérida",
  "hiroshima_JP": "Hiroshima",
  "santiagodelosCaballeros_DO": "Santiago de los Caballeros",
  "shymkent_KZ": "Shymkent",
  "weinan_CN": "Weinan",
  "ghaziabad_IN": "Ghāziābād",
  "matola_MZ": "Matola",
  "dhanbad_IN": "Dhanbad",
  "fes_MA": "Fes",
  "suwon_KR": "Suwon",
  "gustavoAdolfoMadero_MX": "Gustavo Adolfo Madero",
  "nouakchott_MR": "Nouakchott",
  "kisangani_CD": "Kisangani",
  "jiaxing_CN": "Jiaxing",
  "aurangabad_IN": "Aurangabad",
  "omsk_RU": "Omsk",
  "guarulhos_BR": "Guarulhos",
  "bandarLampung_ID": "Bandar Lampung",
  "prague_CZ": "Prague",
  "varanasi_IN": "Varanasi",
  "batam_ID": "Batam",
  "jiujiang_CN": "Jiujiang",
  "samara_RU": "Samara",
  "aba_NG": "Aba",
  "amritsar_IN": "Amritsar",
  "birmingham_GB": "Birmingham",
  "copenhagen_DK": "Copenhagen",
  "sofia_BG": "Sofia",
  "anyang_CN": "Anyang",
  "yerevan_AM": "Yerevan",
  "vijayawada_IN": "Vijayawada",
  "bijie_CN": "Bijie",
  "monterrey_MX": "Monterrey",
  "kigali_RW": "Kigali",
  "rostovnaDonu_RU": "Rostov-na-Donu",
  "zhuzhou_CN": "Zhuzhou",
  "bogor_ID": "Bogor",
  "malingao_PH": "Malingao",
  "touba_SN": "Touba",
  "ufa_RU": "Ufa",
  "ranchi_IN": "Ranchi",
  "baku_AZ": "Baku",
  "shangrao_CN": "Shangrao",
  "lilongwe_MW": "Lilongwe",
  "huaibei_CN": "Huaibei",
  "maiduguri_NG": "Maiduguri",
  "meishan_CN": "Meishan",
  "mwanza_TZ": "Mwanza",
  "sendai_JP": "Sendai",
  "ulsan_KR": "Ulsan",
  "krasnoyarsk_RU": "Krasnoyarsk",
  "guigang_CN": "Guigang",
  "pekanbaru_ID": "Pekanbaru",
  "oslo_NO": "Oslo",
  "jabalpur_IN": "Jabalpur",
  "ilorin_NG": "Ilorin",
  "aden_YE": "Aden",
  "ciudadNezahualcoyotl_MX": "Ciudad Nezahualcoyotl",
  "hengyang_CN": "Hengyang",
  "prayagraj_IN": "Prayagraj",
  "visakhapatnam_IN": "Visakhapatnam",
  "goyangsi_KR": "Goyang-si",
  "yulin_CN": "Yulin",
  "jodhpur_IN": "Jodhpur",
  "gwalior_IN": "Gwalior",
  "jingzhou_CN": "Jingzhou",
  "gqeberha_ZA": "Gqeberha",
  "tbilisi_GE": "Tbilisi",
  "voronezh_RU": "Voronezh",
  "xinxiang_CN": "Xinxiang",
  "yichun_CN": "Yichun",
  "sokoto_NG": "Sokoto",
  "jos_NG": "Jos",
  "tangier_MA": "Tangier",
  "xianyang_CN": "Xianyang",
  "mexicali_MX": "Mexicali",
  "pointeNoire_CG": "Pointe-Noire",
};
